name: onPR

on:
    pull_request:
        types: [opened, synchronize, reopened]
        branches:
            - main
            - develop

concurrency:
    group: ci-pr-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: read
            statuses: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 18
                  cache: npm
                  cache-dependency-path: '**/package-lock.json'

            - name: Install dependencies
              run: npm ci --no-audit --no-fund

            - name: Build
              run: npm run build

            - name: Create issue if build fails
              if: failure()
              uses: JasonEtco/create-an-issue@v2
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
                  ACTION_TYPE: 'Build'
                  URL_ACTION_RUN: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
                  BRANCH: ${{ github.ref }}
              with:
                  assignees: ${{ github.event.sender.login }}

            - name: Comment on PR if failed
              if: failure()
              uses: unsplash/comment-on-pr@v1.3.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
              with:
                  msg: ' Fall贸 el build de la rama :disappointed: 锔. Por favor revisa los errores y toma las medidas necesarias. Action Run: [Action](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})'
            - name: Comment on PR
              uses: unsplash/comment-on-pr@v1.3.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
              with:
                  msg: ' El build ha sido exitoso :+1: :thumbsup:.'

    lint:
        name: Lint
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: read
            statuses: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 18
                  cache: npm
                  cache-dependency-path: '**/package-lock.json'

            - name: Install dependencies
              run: npm ci --no-audit --no-fund

            - name: Lint
              run: npm run lint

            - name: Create issue if lint fails
              if: failure()
              uses: JasonEtco/create-an-issue@v2
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
                  ACTION_TYPE: 'Lint'
                  URL_ACTION_RUN: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
                  BRANCH: ${{ github.ref }}
              with:
                  assignees: ${{ github.event.sender.login }}
            - name: Comment on PR if failed
              if: failure()
              uses: unsplash/comment-on-pr@v1.3.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
              with:
                  msg: ' Fall贸 la verificaci贸n del Lint :dissapointed: 锔. Por favor revisa los errores y toma las medidas necesarias. Action Run: [Action](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})'
            - name: Comment on PR
              uses: unsplash/comment-on-pr@v1.3.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
              with:
                  msg: ' El linter ha verificado el c贸digo :+1: :thumbsup:.'

    test:
        name: Test
        runs-on: ubuntu-latest
        needs: [build, lint]
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 18
                  cache: npm
                  cache-dependency-path: '**/package-lock.json'

            - name: Install dependencies
              run: npm ci --no-audit --no-fund

            - name: Test
              run: npm run test

            - name: Create issue if test fails
              if: failure()
              uses: JasonEtco/create-an-issue@v2
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
                  ACTION_TYPE: 'Test'
                  URL_ACTION_RUN: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
                  BRANCH: ${{ github.ref }}
              with:
                  assignees: ${{ github.event.sender.login }}
            - name: Comment on PR if failed
              if: failure()
              uses: unsplash/comment-on-pr@v1.3.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
              with:
                  msg: ' Fall贸 la verificaci贸n del los Test :dissapointed: 锔. Por favor revisa los errores y toma las medidas necesarias. Action Run: [Action](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})'
            - name: Comment on PR
              uses: unsplash/comment-on-pr@v1.3.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
              with:
                  msg: ' Los test han pasado correctamente :+1: :thumbsup:.'
